compose_error: Allow compose error to stay even after a msg is sent.
Introduced the "stay" attribute to the
"#compose-send-status" element to keep
track of when to disable compose warnings/errors
after the message is sent.