decorator: Fix request.user handling of remote servers.
The refactor in b46af40bd385f13e3731987832f5dd0eda649206 didn't
correctly translate the code for managing request.user and
request._email, resulting in requests for the push notification
bouncer being rejected with this exception:

AttributeError: 'AnonymousUser' object has no attribute 'rate_limits'