config_error: Change the look of the page.
Replaces the green theme with the old Zulip octopus with a plain, white
page.

(cherry picked from commit 2dff547e9936a2f3be09b30f4e9e3846c31ac4eb)