populate_db: Clean up existing RemoteRealm, RemoteZulipServer objects.
As of c9b060232005e34d31e87a35c6a96582f1f88af8 and
8b55d60f9e0365e47dadd4d82b7946e9c8f53149 we create a default
registration for the dev env "RemoteZulipServer" (and also RemoteRealms
for the dev realms) in populate_db. However these models weren't listed
in clear_database, meaning the state wasn't properly cleaned up at the
start of the command.

Most important, this would manifest in getting:
```
django.db.utils.IntegrityError: duplicate key value violates unique
constraint "zilencer_remotezulipserver_uuid_key"
DETAIL:  Key (uuid)=(......) already exists
```

if you re-run populate_db.