Update for compatability with Zabbix 6.0 and newer
Errors when testing media:
ReferenceError: identifier 'CurlHttpRequest' undefined
(property 'AddHeader' of [object Object])

Updated the script to be compatible with 6.0 and newer.
Info about changes in link under:
https://www.zabbix.com/documentation/5.4/en/manual/introduction/whatsnew540#naming